Traceback (most recent call last):
  File "/Users/yirenlu/modal-examples/06_gpu_and_ml/dreambooth/dreambooth_app.py", line 658, in run
    evaluate_model(
  File "/Users/yirenlu/modal-examples/06_gpu_and_ml/dreambooth/dreambooth_app.py", line 428, in evaluate_model
    for image, prompt in Model(hyperparameter_model_dir).inference.starmap(
  File "/opt/homebrew/lib/python3.11/site-packages/modal/_utils/async_utils.py", line 390, in __iter__
    for output in run_async_gen(runner, self._async_iterable):
  File "/opt/homebrew/lib/python3.11/site-packages/modal/_utils/async_utils.py", line 470, in run_async_gen
    next_yield = runner.run(gen.asend(next_send))  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/synchronicity/async_utils.py", line 85, in run
    return self._loop.run_until_complete(wrapper_coro())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/synchronicity/async_utils.py", line 51, in wrapper_coro
    return await coro_task
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/modal/_utils/async_utils.py", line 313, in asend
    return await self.gen.asend(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/modal/parallel_map.py", line 396, in _starmap_async
    async for output in self._map.aio(raw_input_queue, order_outputs, return_exceptions):  # type: ignore[reportFunctionMemberAccess]
  File "/opt/homebrew/lib/python3.11/site-packages/synchronicity/synchronizer.py", line 426, in _run_generator_async
    raise uc_exc.exc
  File "/opt/homebrew/lib/python3.11/site-packages/modal/object.py", line 261, in wrapped
    async for item in stream:
  File "/opt/homebrew/lib/python3.11/site-packages/modal/functions.py", line 1257, in _map
    async for item in stream:
  File "/opt/homebrew/lib/python3.11/site-packages/modal/parallel_map.py", line 86, in _map_invocation
    response = await retry_transient_errors(client.stub.FunctionMap, request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/modal/_utils/grpc_utils.py", line 185, in retry_transient_errors
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/modal/_utils/grpc_utils.py", line 179, in retry_transient_errors
    return await fn(*args, metadata=metadata, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/modal/client.py", line 401, in __call__
    return await self.client._call_unary(self._wrapped_method_name, req, timeout=timeout, metadata=metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/modal/client.py", line 343, in _call_unary
    return await self._call_safely(coro, grpclib_method.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/modal/client.py", line 301, in _call_safely
    return await request_task
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/grpclib/client.py", line 904, in __call__
    reply = await stream.recv_message()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/grpclib/client.py", line 425, in recv_message
    await self.recv_initial_metadata()
  File "/opt/homebrew/lib/python3.11/site-packages/grpclib/client.py", line 393, in recv_initial_metadata
    self._raise_for_grpc_status(status, message, details)
  File "/opt/homebrew/lib/python3.11/site-packages/grpclib/client.py", line 345, in _raise_for_grpc_status
    raise GRPCError(status, message, details)
grpclib.exceptions.GRPCError: (<Status.FAILED_PRECONDITION: 9>, 'The app is stopped or disabled', None)
